import React from "react";
import {
  Typography,
  Button,
  Container,
  Paper,
  Stack,
  Divider,
} from "@mui/material";
import ArrowBackIcon from "@mui/icons-material/ArrowBack";
import NavbarLogo from "./NavbarLogo";

const PrivacyPolicy = ({ onBack }) => {
  return (
    <Container maxWidth="md" sx={{ py: 4 }}>
      <Button
        startIcon={<ArrowBackIcon fontSize="small" />}
        onClick={onBack}
        sx={{ mb: 2 }}
        variant="outlined"
        size="small"
      >
        Back
      </Button>

      <Paper elevation={3} sx={{ p: 4, bgcolor: "background.paper" }}>
        <Stack direction="row" sx={{ justifyContent: "center" }}>
          <Divider sx={{ width: "100%" }}>
            <NavbarLogo src="/logo.png" height={96} hidePadding />
          </Divider>
        </Stack>
        <Typography
          variant="h4"
          gutterBottom
          sx={{ fontWeight: 700, textTransform: "uppercase" }}
        >
          Privacy Policy
        </Typography>

        <Typography variant="body1" paragraph>
          Your privacy is our priority. This Privacy Policy outlines how we
          collect, use, and protect your information when you use our Secure
          Chat Application.
        </Typography>

        <Typography variant="h6" gutterBottom sx={{ fontWeight: 700 }}>
          1. Information We Collect
        </Typography>
        <Typography variant="body2" paragraph>
          We collect basic information necessary to authenticate users and
          provide our services. This includes your account credentials and
          system operational logs generated by our services. We do not collect
          unnecessary personal data.
        </Typography>

        <Typography variant="h6" gutterBottom sx={{ fontWeight: 700 }}>
          2. End-to-End Encryption
        </Typography>
        <Typography variant="body2" paragraph>
          A cornerstone of our application is end-to-end encryption. All chat
          messages, code snippets, and shared file attachments are encrypted on
          your device before transmission. We do not store the decryption keys
          on our servers, meaning that we cannot read your messages or access
          your files under any circumstances.
        </Typography>

        <Typography variant="h6" gutterBottom sx={{ fontWeight: 700 }}>
          3. Use of Information
        </Typography>
        <Typography variant="body2" paragraph>
          The information we collect is used solely to maintain, secure, and
          improve the platform. System logs (such as error and access logs) are
          recorded for troubleshooting, security audits, and ensuring the
          stability of our services.
        </Typography>

        <Typography variant="h6" gutterBottom sx={{ fontWeight: 700 }}>
          4. Data Retention and Deletion
        </Typography>
        <Typography variant="body2" paragraph>
          We retain your encrypted data only as long as necessary to provide our
          services or as required by law. You maintain the right to request the
          deletion of your account and all associated encrypted data from our
          systems at any time.
        </Typography>

        <Typography variant="h6" gutterBottom sx={{ fontWeight: 700 }}>
          5. Third-Party Sharing
        </Typography>
        <Typography variant="body2" paragraph>
          We strictly do not sell, trade, or transfer any of your personally
          identifiable information or communication metadata to outside parties.
          All operations and data storage are contained within our secure
          environment.
        </Typography>

        <Typography variant="h6" gutterBottom sx={{ fontWeight: 700 }}>
          6. Updates to This Policy
        </Typography>
        <Typography variant="body2" paragraph>
          We may update this Privacy Policy to reflect changes in our practices
          or technologies. We encourage you to review this page periodically.
          Continued use of the service implies your consent to the updated
          policy.
        </Typography>
      </Paper>
    </Container>
  );
};

export default React.memo(PrivacyPolicy);
